name: Daily Blockchain Concept

on:
  schedule:
    - cron: '0 19 * * *'  # 12:30 AM IST
    - cron: '0 7 * * *'   # 12:30 PM IST
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Run concept generator
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python daily_generator.py

      - name: Debug Git Remote
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "Before override:"
          git remote -v
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          echo "After override:"
          git remote -v

      - name: Commit and Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "Auto Commit Bot"
          git config --global user.email "bot@example.com"

          git add docs/index.md docs/concepts/*.md
          git commit -m "Daily blockchain concept" || echo "No changes"

          # Inline push with token (bypasses remote fallback)
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:master
