name: Daily Blockchain Concept

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 12:00 AM UTC (5:30 AM IST)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Run concept generator
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python daily_generator.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Daily blockchain concept" || echo "No changes to commit"
          git push
